<?php

/**
 * @file
 * The main module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_field_values_menu() {
  $items['islandora/get_field_values'] = array(
    'title' => 'Get Islandora Solr Field Values',
    'description' => "Query Islandora's Solr index to get a list of all the unique values in a field.",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_field_values_query_form'),
    'access arguments' => array('get unique solr field values'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_field_values_permission() {
  return array(
    'get unique solr field values' => array(
      'title' => t('Get unique Solr field values'),
      'description' => t('Generate a list of unique values in a selected Solr field.'),
    ),
  );
}

function islandora_field_values_query_form() {
  $form = array();
  $form['islandora_field_values_solr_field'] = array(
    '#type' => 'textfield',
    '#description' => t('A field from within Solr. Fields that end in "_ms" show the raw field value and include multivalued values.'),
    '#size' => 105,
    '#autocomplete_path' => 'islandora_solr/autocomplete_luke',
    '#default_value' => '',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit')
  );
  $form['options']['reset'] = array(
    '#type' => 'submit',
    '#value' => t('Reset'),
    '#submit' => array('islandora_field_values_reset'),
  );

  if (isset($_SESSION['islandora_field_values'], $_SESSION['islandora_field_values']['results'])) {
    $fieldname = $_SESSION['islandora_field_values']['field'];
    module_load_include('inc', 'islandora_solr', 'includes/utilities');
    $values = array();
    foreach ($_SESSION['islandora_field_values']['results'] as $value => $count) {
      $facet_escaped_value = islandora_solr_facet_query_escape($value);
      $query = 'islandora/search/' . $fieldname . urlencode(':("' . $facet_escaped_value . '")');
      $link = l(strip_tags($value), $query, array('html' => TRUE));
      $values[] = $link . ' (' . $count . ')';
    }
    $num_values = count($values);
    $list_variables = array(
        'items' => $values,
        'title' => t('@count unique values in the %fieldname Solr field, with occurance counts:', array('@count' => $num_values, '%fieldname' => $fieldname)),
        'type' => 'ul',
        'attributes' => array(),
    );
    if (count($_SESSION['islandora_field_values']['results']) > 0) {
      $results = theme_item_list($list_variables);
    }
    else {
      $results = t("Sorry, that field does not have any values.");
    }
    $form['results'] = array(
      '#markup' => $results,
      '#prefix' => '<div>',
      '#suffix' => '</div>',
    );
  }

  unset($_SESSION['islandora_field_values']);
  return $form;
}

function islandora_field_values_query_form_submit($form, &$form_state) {
  module_load_include('inc', 'islandora_field_values', 'includes/utilities');
  $fieldname = $form_state['values']['islandora_field_values_solr_field'];
  if ($results = islandora_field_values_query_solr($fieldname)) {
    $_SESSION['islandora_field_values']['results'] = $results;
    $_SESSION['islandora_field_values']['field'] = $fieldname;
  }
}

function islandora_field_values_reset($form, &$form_state) {
  $form_state['rebuild'] = FALSE;
}
